### ISSUE TITLE
Quetsion: Leaking firebase credentials

### ISSUE THREAD

**Issue by sinclairnick** [vriad/next-firebase-ssr#14]
Won't using this method leak your credentials to the front end? Wouldn't it be better to use API routes to isolate the use of firebase admin to the server-side only?

**Comment by colinhacks** [comment]
This approach doesn't leak credentials to the front-end. I assume you're looking at `authenticated.tsx`. In Next.js you can import server-side variables into pages, and as long as you only use them inside `getServerSideProps`, Next will strip them out of the client side bundle. From https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering:

![Screen Shot 2021-03-18 at 12 14 15 PM](https://user-images.githubusercontent.com/3084745/111676125-79757980-87e3-11eb-9998-81f5aee1bc06.png)
